version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: elou-avt-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: elou-avt
    volumes:
      - mongodb_data:/data/db
    networks:
      - elou-network

volumes:
  mongodb_data:
    driver: local

networks:
  elou-network:
    driver: bridge
